spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: true

  servlet:
    multipart:
      max-file-size: 10GB      # 업로드 파일 최대 크기
      max-request-size: 10GB   # 요청 당 최대 크기

cloudinary:
  cloud_name: "${CLOUDINARY_CLOUD_NAME}"
  api_key: "${CLOUDINARY_API_KEY}"
  api_secret: "${CLOUDINARY_API_SECRET}"